import Providers from "./providers/Providers";
import "primeicons/primeicons.css";
import type { Metadata } from "next";
// import localFont from "next/font/local";
import {Inter} from 'next/font/google'
import "./globals.css";


const OpenSans = Inter({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Providers>
      <body
        className={`${OpenSans.className} antialiased`}
      >
       {children}
      </body>
      </Providers>
    </html>
  );
}
